//============================================================================================================
//
// Header file for the system flag definitions
//
//============================================================================================================
#ifndef _W_MAG_H_
#define _W_MAG_H_

// Cluster Define
#define _CLUSTER_WIDTH  1280
#define _CLUSTER_STRIDE 1280
#define _CLUSTER_Hight  480


//---------------------------------
#define _CHECK_ICON_NUM_MAX 10

#define _SHIFTER_P 0x01
#define _SHIFTER_R 0x02
#define _SHIFTER_N 0x03
#define _SHIFTER_D 0x04
#define _DRIVE_TURTLE 0x00
#define _DRIVE_ECO 0x01
#define _DRIVE_SPORT 0x03
#define _DOOR_BG 0x00
#define _DOOR_FRONT_LEFT 0x01
#define _DOOR_FRONT_RIGHT 0x02
#define _DOOR_REAR_LEFT 0x03
#define _DOOR_REAR_RIGHT 0x04
#define _DOOR_REAR_TAIL 0x05

#define _PIC_SHIFT_ADDR 0x08
//Picture address
#ifdef _MARS
#define _PIC_START_ADDR       	                0x60000000
#endif
#ifdef _MAG
#define _PIC_START_ADDR       	                0x10000000
#endif

#define _PIC_BASE       (_PIC_START_ADDR - _PIC_SHIFT_ADDR)
#define	_PIC_BACKGROUND_RLE		_PIC_BASE + 0x100


/* MARS */
#define _CLUSTER_PIC_START_ADDR             0x60000000
#define _CLUSTER_STANDARD_BACKGROUND_ADDR   _CLUSTER_PIC_START_ADDR + 0x000e1b00
#define _CLUSTER_SPORT_BACKGROUND_ADDR      _CLUSTER_PIC_START_ADDR + 0x0000d300
#define _CLUSTER_ICON_BATERY_ADDR           _CLUSTER_PIC_START_ADDR + 0x00000000
#define _CLUSTER_ICON_ENGINE_OIL_ADDR       _CLUSTER_PIC_START_ADDR + 0x00000f00
#define _CLUSTER_ICON_FOG_LIGHT_ADDR        _CLUSTER_PIC_START_ADDR + 0x00001e00
#define _CLUSTER_ICON_HIGHT_BEAM_ADDR       _CLUSTER_PIC_START_ADDR + 0x00002d00
#define _CLUSTER_ICON_HOOD_ADDR             _CLUSTER_PIC_START_ADDR + 0x00003c00
#define _CLUSTER_ICON_LOW_BEAM_ADDR         _CLUSTER_PIC_START_ADDR + 0x00004b00
#define _CLUSTER_ICON_SEATBELT_ADDR         _CLUSTER_PIC_START_ADDR + 0x00005a00
#define _CLUSTER_ICON_SNOW_ADDR             _CLUSTER_PIC_START_ADDR + 0x00006900
#define _CLUSTER_ICON_TURN_LEFT_ADDR        _CLUSTER_PIC_START_ADDR + 0x00007800
#define _CLUSTER_ICON_TURN_RIGHT_ADDR       _CLUSTER_PIC_START_ADDR + 0x00008700
#define _CLUSTER_ICON_WIPER_ADDR            _CLUSTER_PIC_START_ADDR + 0x00009600
#define _CLUSTER_ICON_WIPER_FLUID_ADDR      _CLUSTER_PIC_START_ADDR + 0x0000a500
#define _CLUSTER_POINTER_BIG_ADDR           _CLUSTER_PIC_START_ADDR + 0x0000b400
#define _CLUSTER_POINTER_SMALL_ADDR         _CLUSTER_PIC_START_ADDR + 0x0000cd00
#define _CLUSTER_SPORT_BIG_GEAR_D_ADDR      _CLUSTER_PIC_START_ADDR + 0x000bb100
#define _CLUSTER_SPORT_BIG_GEAR_N_ADDR      _CLUSTER_PIC_START_ADDR + 0x000bfe00
#define _CLUSTER_SPORT_BIG_GEAR_P_ADDR      _CLUSTER_PIC_START_ADDR + 0x000c4b00
#define _CLUSTER_SPORT_BIG_GEAR_R_ADDR      _CLUSTER_PIC_START_ADDR + 0x000c9800
#define _CLUSTER_SPORT_SMALL_GEAR_D_ADDR    _CLUSTER_PIC_START_ADDR + 0x000d0300
#define _CLUSTER_SPORT_SMALL_GEAR_N_ADDR    _CLUSTER_PIC_START_ADDR + 0x000d1200
#define _CLUSTER_SPORT_SMALL_GEAR_P_ADDR    _CLUSTER_PIC_START_ADDR + 0x000d2100
#define _CLUSTER_SPORT_SMALL_GEAR_R_ADDR    _CLUSTER_PIC_START_ADDR + 0x000d3000
#define _CLUSTER_SPORT_Km_h_ADDR            _CLUSTER_PIC_START_ADDR + 0x000ce500
#define _CLUSTER_SPORT_SPEED_NUM0_ADDR      _CLUSTER_PIC_START_ADDR + 0x000d3f00
#define _CLUSTER_SPORT_SPEED_NUM1_ADDR      _CLUSTER_PIC_START_ADDR + 0x000d5500
#define _CLUSTER_SPORT_SPEED_NUM2_ADDR      _CLUSTER_PIC_START_ADDR + 0x000d6b00
#define _CLUSTER_SPORT_SPEED_NUM3_ADDR      _CLUSTER_PIC_START_ADDR + 0x000d8100
#define _CLUSTER_SPORT_SPEED_NUM4_ADDR      _CLUSTER_PIC_START_ADDR + 0x000d9700
#define _CLUSTER_SPORT_SPEED_NUM5_ADDR      _CLUSTER_PIC_START_ADDR + 0x000dad00
#define _CLUSTER_SPORT_SPEED_NUM6_ADDR      _CLUSTER_PIC_START_ADDR + 0x000dc300
#define _CLUSTER_SPORT_SPEED_NUM7_ADDR      _CLUSTER_PIC_START_ADDR + 0x000dd900
#define _CLUSTER_SPORT_SPEED_NUM8_ADDR      _CLUSTER_PIC_START_ADDR + 0x000def00
#define _CLUSTER_SPORT_SPEED_NUM9_ADDR      _CLUSTER_PIC_START_ADDR + 0x000e0500
#define _CLUSTER_STANDARD_GEAR_D_ADDR       _CLUSTER_PIC_START_ADDR + 0x0018e400
#define _CLUSTER_STANDARD_GEAR_N_ADDR       _CLUSTER_PIC_START_ADDR + 0x0018f300
#define _CLUSTER_STANDARD_GEAR_P_ADDR       _CLUSTER_PIC_START_ADDR + 0x00190200
#define _CLUSTER_STANDARD_GEAR_R_ADDR       _CLUSTER_PIC_START_ADDR + 0x00191100

void W_MAG_Init(void);
void W_MAG_Logo_Disp(void);
void W_MAG_Draw2D_Process(void);
void W_MAG_WindowSwap(void);

#endif
