/****************************************************************************
 *  License : All rights reserved for TES Electronic Solutions GmbH
 *            See included /docs/license.txt for details
 *  Project : D/AVE HD
 *  Purpose : Hardware specific compiletime settings
 ****************************************************************************
 * Version Control Information :
 *  $Revision: 9286 $
 *  $Date: 2016-07-07 12:54:47 +0200 (Do, 07 Jul 2016) $
 *  $LastChangedBy: michael.golczewski $
 ****************************************************************************
 * Change History (autogenerated):
 ****************************************************************************/
/*----------------------------------------------------------------------------------------------------------*/
/* Renesas D1x Platform gets platform constrained registerfile, default config for all other*/
/**/

#ifndef DAVEHD_REGISTERFILE_H_INCLUDED
#define DAVEHD_REGISTERFILE_H_INCLUDED


#ifdef RENESAS_D1X
  #include "davehd_registerfile_ree.h"
#else
  #include "davehd_registerfile_default.h"
#endif

#endif /* DAVEHD_REGISTERFILE_H_INCLUDED */
